[package]
name = "voxel-content"
version = "0.1.0"
edition = "2024"

[dependencies]
dot_vox = "5.2.0"
bevy = { workspace = true }
bevy_egui = "0.39"
voxel-data = { version = "0.1.0", path = "../voxel-data" }
voxel-edit = { version = "0.1.0", path = "../voxel-edit" }
voxel-sources = { version = "0.1.0", path = "../voxel-sources" }
voxel-streaming = { version = "0.1.0", path = "../voxel-streaming" }
voxel-lightyear = { version = "0.1.0", path = "../voxel-lightyear" }
