[package]
name = "camera-voxel-loader"
version = "0.1.0"
edition = "2024"

[features]
default = []
tracy = ["tracy-client/enable"]

[dependencies]
bevy = { workspace = true }
tracy-client = { workspace = true }
voxel-data = { version = "0.1.0", path = "../voxel-data" }
tile-data = { version = "0.1.0", path = "../tile-data" }
voxel-streaming = { version = "0.1.0", path = "../voxel-streaming" }

[dev-dependencies]
dot_vox = "5.2.0"
voxel-sources = { version = "0.1.0", path = "../voxel-sources" }

[lints]
workspace = true
