[package]
name = "voxel-gpu"
version = "0.1.0"
edition = "2024"

[features]
default = []
tracy = ["tracy-client/enable"]
gpu_profiling = []

[dependencies]
rand = "0.10.1"
clone_cell = "0.4.2"
parry3d = "0.26.0"
log = { workspace = true }
wgpu = { workspace = true }
num = { workspace = true }
bytemuck = { workspace = true }
bitflags = { workspace = true }
tracy-client = { workspace = true }
bevy = { workspace = true }
orderly-allocator = "0.2.2"
voxel-data = { version = "0.1.0", path = "../voxel-data" }
voxel-tasks = { version = "0.1.0", path = "../voxel-tasks" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = ["console"] }
getrandom = { workspace = true }
getrandom_0_3 = { workspace = true }
wgpu = { workspace = true, features = ["webgpu"] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lints]
workspace = true
