[workspace]
resolver = "3"

members = [
	"crates/voxel-tasks",
	"crates/voxel-data",
	"crates/tile-data",
	"crates/voxel-edit",
	"crates/voxel-gpu",
	"crates/voxel-streaming",
	"crates/camera-voxel-loader",
	"crates/voxel-sources",
	"crates/voxel-lightyear",
	"crates/voxel-ray-renderer",
	"crates/voxel-raster-renderer",
	"crates/voxel-marching-renderer",
	"crates/voxel-physics",
	"crates/voxel-content",
	"crates/basic-voxel",
	"crates/voxel-app",
	"crates/voxel-engine",
	"crates/bevy-web-worker",
]

default-members = [
	"crates/voxel-app",
]

[profile.release]
strip = true

[workspace.dependencies]
bevy = "0.19"
bevy_ecs = "0.19"
bevy-trait-query = "0.19"
crossbeam-channel = "0.5.15"
wgpu = "29.0.3"
log = "0.4"
num = "0.4.3"
bytemuck = { version = "1.24", features = ["derive"] }
bitflags = "2.13"
tracy-client = { version = "0.18.4", default-features = false }
rustc-hash = "2.1.2"
tokio = "1"
futures = "0.3.32"
getrandom = { version = "0.4", features = ["wasm_js"] }
getrandom_0_3 = { package = "getrandom", version = "0.3", features = ["wasm_js"] }

[workspace.lints.clippy]
type_complexity = "allow"
too_many_arguments = "allow"
collapsible_if = "allow"
