[workspace]
resolver = "3"

members = [
	"crates/core/voxel-tasks",
	"crates/core/voxel-trees",
	"crates/core/voxel-data",
	"crates/core/tile-data",
	"crates/core/voxel-sources",
	"crates/core/voxel-streaming",
	"crates/engine/voxel-gpu",
	"crates/engine/voxel-query",
	"crates/engine/camera-voxel-loader",
	"crates/engine/voxel-lightyear",
	"crates/engine/voxel-ray-renderer",
	"crates/engine/voxel-raster-renderer",
	"crates/engine/voxel-marching-renderer",
	"crates/engine/voxel-physics",
	"crates/engine/voxel-mass",
	"crates/engine/voxel-content",
	"crates/engine/basic-voxel",
	"crates/engine/voxel-engine",
	"crates/bevy-web-worker",
	"crates/voxel-app",
]

default-members = [
	"crates/voxel-app",
]

[profile.release]
strip = true

[workspace.dependencies]
bevy = "0.19"
bevy_ecs = "0.19"
crossbeam-channel = "0.5.15"
wgpu = "29.0.3"
log = "0.4"
num = "0.4.3"
bytemuck = { version = "1.24", features = ["derive"] }
bitflags = "2.13"
tracy-client = { version = "0.18.4", default-features = false }
rustc-hash = "2.1.2"
tokio = "1"
futures = "0.3.32"
getrandom = { version = "0.4", features = ["wasm_js"] }
getrandom_0_3 = { package = "getrandom", version = "0.3", features = ["wasm_js"] }
voxel-tasks = { version = "0.1.0", path = "crates/core/voxel-tasks" }
voxel-trees = { version = "0.1.0", path = "crates/core/voxel-trees" }
voxel-data = { version = "0.1.0", path = "crates/core/voxel-data" }
tile-data = { version = "0.1.0", path = "crates/core/tile-data" }
voxel-sources = { version = "0.1.0", path = "crates/core/voxel-sources" }
voxel-streaming = { version = "0.1.0", path = "crates/core/voxel-streaming" }
voxel-gpu = { version = "0.1.0", path = "crates/engine/voxel-gpu" }
voxel-query = { version = "0.1.0", path = "crates/engine/voxel-query" }
camera-voxel-loader = { version = "0.1.0", path = "crates/engine/camera-voxel-loader" }
voxel-lightyear = { version = "0.1.0", path = "crates/engine/voxel-lightyear" }
voxel-ray-renderer = { version = "0.1.0", path = "crates/engine/voxel-ray-renderer" }
voxel-raster-renderer = { version = "0.1.0", path = "crates/engine/voxel-raster-renderer" }
voxel-marching-renderer = { version = "0.1.0", path = "crates/engine/voxel-marching-renderer" }
voxel-physics = { version = "0.1.0", path = "crates/engine/voxel-physics" }
voxel-mass = { version = "0.1.0", path = "crates/engine/voxel-mass" }
voxel-content = { version = "0.1.0", path = "crates/engine/voxel-content" }
basic-voxel = { version = "0.1.0", path = "crates/engine/basic-voxel" }
voxel-engine = { version = "0.1.0", path = "crates/engine/voxel-engine" }

[workspace.lints.clippy]
type_complexity = "allow"
too_many_arguments = "allow"
collapsible_if = "allow"
