max_width = 150
use_small_heuristics = "Max"
fn_call_width = 150
fn_params_layout = "Compressed"
struct_lit_width = 150
struct_variant_width = 150
chain_width = 150
overflow_delimited_expr = false
brace_style = "SameLineWhere"
fn_single_line = true
control_brace_style = "AlwaysSameLine"
match_arm_leading_pipes = "Never"
match_block_trailing_comma = false
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
reorder_imports = true
reorder_modules = false
format_code_in_doc_comments = true
normalize_comments = true
wrap_comments = false
