[package]
name = "voxel-raster-renderer"
version = "0.1.0"
edition = "2024"

[features]
default = []
shader_hot_reload = ["bevy/embedded_watcher"]

[dependencies]
log = { workspace = true }
wgpu = { workspace = true }
bytemuck = { workspace = true }
bevy = { workspace = true }
voxel-data = { version = "0.1.0", path = "../voxel-data" }
tile-data = { version = "0.1.0", path = "../tile-data" }
voxel-gpu = { version = "0.1.0", path = "../voxel-gpu" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wgpu = { workspace = true, features = ["webgpu"] }
getrandom = { workspace = true }
getrandom_0_3 = { workspace = true }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lints]
workspace = true
