[package]
name = "voxel-data"
version = "0.1.0"
edition = "2024"

[features]
default = []
tracy = ["tracy-client/enable"]
gpu_profiling = []

[dependencies]
bimap = "0.6.3"
async-priority-queue = "0.1.1"
crossbeam-channel = "0.5.15"
bevy = { workspace = true }
tracy-client = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "grid_tree"
harness = false

[[bench]]
name = "splat_voxels"
harness = false

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { workspace = true }
getrandom_0_3 = { workspace = true }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
