[package]
name = "voxel-data"
version = "0.1.0"
edition = "2024"

[features]
default = []
tracy = ["tracy-client/enable"]
gpu_profiling = []

[dependencies]
bimap = { version = "0.6.3", features = ["serde"] }
async-priority-queue = "0.1.1"
crossbeam-channel = "0.5.15"
futures = "0.3.32"
bevy = { workspace = true }
bincode = "1.3"
lz4_flex = { version = "0.11", default-features = false }
serde = { version = "1", features = ["derive"] }
serde-big-array = "0.5"
tracy-client = { workspace = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "grid_tree"
harness = false

[[bench]]
name = "splat_voxels"
harness = false

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.114"
js-sys = "0.3"
wasm_thread = { version = "0.3", features = ["es_modules"] }
web-sys = { version = "0.3", features = ["console"] }
getrandom = { workspace = true }
getrandom_0_3 = { workspace = true }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
