[package]
name = "voxel-data"
version = "0.1.0"
edition = "2024"

[profile.release]
strip = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
tracy = ["tracy-client/enable"]
gpu_profiling = []

[dependencies]
glam = "0.30.10"
bimap = "0.6.3"
tracy-client = { version = "0.18.4", default-features = false }
tokio = { version = "1", features = ["full"] }
async-priority-queue = "0.1.1"
bevy = "0.18.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.4", features = ["wasm_js"] } # dep of rand
getrandom_0_3 = { package = "getrandom", version = "0.3", features = ["wasm_js"] } # dep of dot_vox

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
