[package]
name = "voxel-app"
version = "0.1.0"
edition = "2024"

[profile.release]
strip = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
gpu_profiling = []

[dependencies]
glam = "0.30.10"
log = "0.4"
dot_vox = "5.2.0"
nalgebra = "0.34.1"
rtrb = "0.3.2"
tokio = { version = "1", features = ["full"] }
bevy = "0.18.1"
bevy_egui = "0.39"
voxel-renderer = { version = "0.1.0", path = "../voxel-renderer" }
voxel-data = { version = "0.1.0", path = "../voxel-data" }
gpu-voxel-data = { version = "0.1.0", path = "../gpu-voxel-data" }
voxel-physics = { version = "0.1.0", path = "../voxel-physics" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cpal = "0.16"

[target.'cfg(target_arch = "wasm32")'.dependencies]
cpal = { version = "0.16", features = ["wasm-bindgen"] }
getrandom = { version = "0.4", features = ["wasm_js"] } # dep of rand
getrandom_0_3 = { package = "getrandom", version = "0.3", features = ["wasm_js"] } # dep of dot_vox
console_error_panic_hook = "0.1.7"
console_log = "1.0"
wasm-bindgen = "0.2.114"
wasm-bindgen-futures = "0.4.64"
web-time = "1.1.0"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
