[package]
name = "voxel-transform"
version = "0.1.0"
edition = "2024"

[features]
default = []
tracy = ["tracy-client/enable"]

[dependencies]
bevy = { version = "0.19.0", default-features = false, features = ["std", "bevy_camera", "serialize", "multi_threaded"] }
fixed = "1.30"
serde = { version = "1", features = ["derive"] }
tracy-client = { workspace = true }
voxel-math = { workspace = true }
voxel-data = { workspace = true }

[lints]
workspace = true
