[package]
name = "voxel-physics"
version = "0.1.0"
edition = "2024"

[features]
default = []
tracy = ["tracy-client/enable"]
gpu_profiling = []

[dependencies]
num = { workspace = true }
tracy-client = { workspace = true }
rustc-hash = { workspace = true }
bevy = { workspace = true }
voxel-data = { version = "0.1.0", path = "../voxel-data" }
tile-data = { version = "0.1.0", path = "../tile-data" }
voxel-streaming = { version = "0.1.0", path = "../voxel-streaming" }
voxel-sources = { version = "0.1.0", path = "../voxel-sources" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { workspace = true }
getrandom_0_3 = { workspace = true }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lints]
workspace = true
