[package]
name = "voxel-renderer"
version = "0.1.0"
edition = "2024"

[features]
default = []
gpu_profiling = []

[dependencies]
anyhow = "1.0"
log = { workspace = true }
wgpu = { workspace = true }
bytemuck = { workspace = true }
bevy = { workspace = true }
voxel-data = { version = "0.1.0", path = "../voxel-data" }
gpu-voxel-data = { version = "0.1.0", path = "../gpu-voxel-data" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { workspace = true }
getrandom_0_3 = { workspace = true }
wgpu = { workspace = true, features = ["webgpu"] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
