use std::sync::Arc;

use bevy::prelude::*;

use tile_data::NonZeroChunkRegion;
use voxel_data::grid::GridId;
use voxel_data::voxels::{VoxelTypeId, Voxels};
use voxel_tasks::CancellationToken;

use super::handle::SourceHandle;

pub(super) type SharedSource = Arc<dyn ChunkSource>;

pub struct TakeJob {
	chunk: IVec3,
	run: Box<dyn FnOnce() + Send + 'static>,
}

impl TakeJob {
	pub fn new(chunk: IVec3, run: impl FnOnce() + Send + 'static) -> Self {
		Self { chunk, run: Box::new(run) }
	}

	pub fn chunk(&self) -> IVec3 { self.chunk }

	pub(super) fn run(self) { (self.run)(); }
}

/// How much of a requested chunk-space region a source owns. Coverage is
/// independent of whether the generated voxel data is empty or sparse.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SourceCoverage {
	/// The source owns none of the requested region and started no request.
	None,
	/// The source owns part of the region and started an asynchronous request.
	Some,
	/// The source owns the entire region and started an asynchronous request.
	All,
}

impl SourceCoverage {
	pub fn from_count(owned: usize, total: usize) -> Self {
		if owned == 0 { Self::None } else if owned == total { Self::All } else { Self::Some }
	}

	pub fn has_any(self) -> bool { self != Self::None }
}

/// A source of voxel chunks. Sources own their ownership state; SourceManager
/// coordinates permanent transfers and routes requests through the sources
/// that currently offer data.
pub trait ChunkSource: Send + Sync {
	fn init(&self, handle: SourceHandle);

	fn request_load(
		&self,
		grid: GridId,
		chunk: IVec3,
		generation: u64,
		cancellation: CancellationToken,
	) -> SourceCoverage;

	fn request_voxel_area(
		&self,
		grid: GridId,
		region: NonZeroChunkRegion,
		lod: f32,
		voxel_type: VoxelTypeId,
		generation: u64,
		cancellation: CancellationToken,
	) -> SourceCoverage;

	fn request_available_area(&self, grid: GridId);

	/// Atomically relinquish every owned chunk in an area and return threaded
	/// jobs that emit each chunk's data individually to `destination`.
	fn take(&self, grid: GridId, region: NonZeroChunkRegion) -> Vec<TakeJob>;

	/// Queue data generated by a chunk's previous owner. This must not block;
	/// the destination keeps the chunk not-ready until it installs the data.
	fn receive_taken(&self, grid: GridId, chunk: IVec3, voxels: Option<Voxels>) {
		let _ = (grid, chunk, voxels);
		panic!("source does not support taking chunks");
	}

	/// Persist data at an already-assigned chunk generation. Saving transfers
	/// ownership but does not edit the chunk or publish a command event.
	fn save(&self, grid: GridId, chunk: IVec3, generation: u64, voxels: &Voxels) -> bool {
		let _ = (grid, chunk, generation, voxels);
		false
	}

	/// Relinquish ownership of the chunk immediately.
	fn forget(&self, grid: GridId, chunk: IVec3);
}
